apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-site
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-site
  template:
    metadata:
      labels:
        app: pet-site
    spec:
      containers:
      - name: pet-site
        image: ahmedmoali/production-engineering-tools:v1
        env:
        - name: SPRING_APPLICATION_JSON
          value: "{\"representatives\":{\"rest\":{\"endpoint\":{\"url\":\"http://www.mocky.io/v2/5df917f5300000d45688a1b4\"}}},\"companies\":{\"rest\":{\"endpoint\":{\"url\":\"http://www.mocky.io/v2/5df8fc57300000d45688a10e\"}}}}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080